meta_name: "KIEZ"
meta_product_name: "KIEZ"
meta_title: "KIEZ - bringing community together through better communication"
meta_description: "KIEZ - bringing community together through better communication"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@twitter"   # required for Twitter Cards
